<?php

/**
 * @file
 * CAPx Tamper Module.
 */

include_once 'views/capx_tamper.views_default_alter.inc';

use \CAPx\Drupal\Util\CAPx;
use \CAPx\Drupal\Entities\CFEntity;
use \CAPx\Drupal\Mapper\EntityMapper;

define('CAPX_TAMPER', 'admin/config/capx/mapper');

/**
 * Implements hook_ctools_plugin_api().
 */
function capx_tamper_ctools_plugin_api($owner, $api) {
  if ($owner == 'mymodule' && $api == 'capx_tamper') {
    return array('version' => 1);
  }
}

/**
 * Implements hook_theme().
 */
function capx_tamper_theme($existing, $type, $theme, $path) {
  return array(
    'capx_tamper_list_form' => array(
      'render element' => 'form',
      'file' => 'capx_tamper.theme.inc',
    ),
  );
}

/**
 * Implements hook_views_data_alter().
 */
function capx_tamper_views_data_alter(&$data) {
  // Tampers link.
  $data['capx_cfe']['tamper_link'] = array(
    'title' => t('Manage Tampers link'),
    'help' => t('Manage Tampers link for mappings'),
    'field' => array(
      'handler' => 'views_handler_tamper_link',
    ),
  );
}

/**
 * Implements hook_menu().
 */
function capx_tamper_menu() {
  $items = array();

  $items[CAPX_TAMPER . '/%capx_tamper_mapper/tamper'] = array(
    'title' => 'Tampers',
    'page callback' => 'capx_tamper_build_form',
    'page arguments' => array('list', 4),
    'file' => 'capx_tamper.forms.inc',
    'access arguments' => array('administer capx'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items[CAPX_TAMPER . '/%capx_tamper_mapper/tamper/add/%'] = array(
    'title' => 'Add Tamper',
    'page callback' => 'capx_tamper_build_form',
    'page arguments' => array(6, 4, 7),
    'file' => 'capx_tamper.forms.inc',
    'access arguments' => array('administer capx'),
    'type' => MENU_CALLBACK,
  );

  $items[CAPX_TAMPER . '/%capx_tamper_mapper/tamper/%/edit'] = array(
    'title' => 'Tampers',
    'page callback' => 'capx_tamper_build_form',
    'page arguments' => array(7, 4, 6),
    'file' => 'capx_tamper.forms.inc',
    'access arguments' => array('administer capx'),
    'type' => MENU_CALLBACK,
  );

  $items[CAPX_TAMPER . '/%capx_tamper_mapper/tamper/%/delete'] = array(
    'title' => 'Tampers',
    'page callback' => 'capx_tamper_build_form',
    'page arguments' => array(7, 4, 6),
    'file' => 'capx_tamper.forms.inc',
    'access arguments' => array('administer capx'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Loader for menu & pages.
 *
 * @param string $mapper_id
 *   Machine name of the Capx Mapper.
 *
 * @return \CAPx\Drupal\Entities\CFEntity
 *   CAPx Mapper.
 */
function capx_tamper_mapper_load($mapper_id) {
  $mapper = capx_cfe_load_by_machine_name($mapper_id, 'mapper');
  if (!$mapper) {
    drupal_not_found();
    drupal_exit();
  }
  return $mapper;
}

/**
 * Takes the configurations of the CAPx Mapper and gives the available sources.
 *
 * @param CFEntity $mapper
 *   CAPx Mapper to collect available sources.
 *
 * @return array
 *   Associative array of keys as json paths. Values as an array of targets.
 */
function capx_tamper_get_mapper_sources(CFEntity $mapper) {
  $sources = array();
  foreach ($mapper->properties as $property => $path) {
    $sources[$path][] = $property;
  }

  foreach ($mapper->fields as $field_key => $field_settings) {
    $field_settings = array_filter($field_settings);
    if ($field_settings) {
      $path = $field_settings[key($field_settings)];
      $sources[$path][] = $field_key;
    }
  }
  return $sources;
}

/**
 * Implements hook_entity_load().
 */
function capx_tamper_entity_load($entities, $type) {
  if ($type == 'capx_cfe') {
    foreach ($entities as &$entity) {
      if ($entity->type == 'mapper') {
        $entity->tampers = capx_tamper_load_tampers(array('mapper' => $entity->machine_name));
      }
    }
  }
}

/**
 * Implements hook_entity_insert().
 */
function capx_tamper_entity_insert($entity, $type) {
  if ($type == 'capx_cfe' && $entity->type == 'mapper' && isset($entity->tampers)) {
    foreach ($entity->tampers as $tamper) {
      capx_tamper_save_instance($tamper);
    }

  }
}

/**
 * Implements hook_entity_update().
 *
 * If the source does not exist after saving the mapper, delete any CAPx Tamper
 * plugins that are attached.
 */
function capx_tamper_entity_update($entity, $type) {
  if ($type == 'capx_cfe' && $entity->type == 'mapper' && isset($entity->tampers)) {
    /** @var \CAPx\Drupal\Entities\CFEntity $entity */
    $sources = capx_tamper_get_mapper_sources($entity);
    foreach ($entity->tampers as $id => $tamper) {
      if (!isset($sources[$tamper->source])) {
        capx_tamper_delete_instance($tamper);
      }
    }
  }
}

/**
 * Implements hook_entity_delete().
 *
 * Deletes any CAPx Tamper plugins when the mapper is deleted.
 */
function capx_tamper_entity_delete($entity, $type) {
  if ($type == 'capx_cfe' && $entity->type == 'mapper' && isset($entity->tampers)) {
    /** @var \CAPx\Drupal\Entities\CFEntity $entity */
    foreach ($entity->tampers as $tamper) {
      capx_tamper_delete_instance($tamper);
    }
  }
}

/**
 * Load a single or all capx tamper plugins.
 *
 * @param array $conditions
 *   Keyed conditions of the tampers to load.
 *   'mapper' => mapper machine name.
 *   'id' => tamper id.
 *   'source' => field name or entity property.
 *
 * @return array
 *   Single or all tampers configured.
 */
function capx_tamper_load_tampers($conditions = array()) {
  ctools_include('export');
  if ($conditions) {
    $items = ctools_export_load_object('capx_tamper', 'conditions', $conditions);
  }
  else {
    $items = ctools_export_load_object('capx_tamper');
  }

  $disabled = variable_get('capx_tamper_disabled', array());
  foreach ($items as &$tamper) {
    $tamper->disabled = FALSE;
    if (isset($disabled[$tamper->id])) {
      $tamper->disabled = TRUE;
    }
  }

  usort($items, function ($a, $b) {
    return $a->weight - $b->weight;
  });

  return $items;
}

/**
 * Saves the tamper plugin and settings.
 *
 * @param object $tamper
 *   CAPx Tamper object.
 */
function capx_tamper_save_instance($tamper) {
  if (capx_tamper_load_tampers(array('id' => $tamper->id))) {
    drupal_write_record('capx_tamper', $tamper, 'id');
  }
  else {
    drupal_write_record('capx_tamper', $tamper);
  }
  capx_tamper_invalidate_etags($tamper->mapper);
}

/**
 * Deletes the given CAPx Tamper plugin.
 *
 * @param object $tamper
 *   CAPx Tamper plugin to delete.
 */
function capx_tamper_delete_instance($tamper) {
  db_delete('capx_tamper')
    ->condition('id', $tamper->id)
    ->condition('mapper', $tamper->mapper)
    ->execute();

  $disabled = variable_get('capx_tamper_disabled', array());
  unset($disabled[$tamper->id]);
  variable_set('capx_tamper_disabled', $disabled);
  capx_tamper_invalidate_etags($tamper->mapper);
}

/**
 * Invalidates etags when a tamper is created, edited, or deleted.
 *
 * @param string $mapper_id
 *   Machine name of the mapper to invalidate.
 */
function capx_tamper_invalidate_etags($mapper_id) {
  /** @var \CAPx\Drupal\Entities\CFEntity $mapper */
  $mapper = capx_tamper_mapper_load($mapper_id);
  CAPx::invalidateEtags('mapper', $mapper);
}

/**
 * Implements hook_capx_pre_update_entity_alter().
 */
function capx_tamper_capx_pre_update_entity_alter(&$entity, &$data, EntityMapper &$mapper) {
  $values = array(
    'data' => $data,
    'mapper' => $mapper,
  );
  capx_tamper_capx_pre_entity_create_alter($values);
  $data = $values['data'];
}

/**
 * Implements hook_capx_pre_entity_create_alter().
 *
 * Change the entries in the $values['data'] according to the tamper plugins.
 */
function capx_tamper_capx_pre_entity_create_alter(&$values) {
  /** @var EntityMapper $mapper */
  $mapper = NULL;
  $data = array();
  extract($values);
  /** @var CFEntity $cfe_mapper */
  $cfe_mapper = $mapper->getMapper();
  // Sets an object to be used for particular tamper plugins.
  // @see feeds_tamper_copy_callback().
  $result = new stdClass();
  $items = array();
  foreach (capx_tamper_get_mapper_sources($cfe_mapper) as $path => $targets) {
    $item = $mapper->getRemoteDataByJsonPath($data, $path);
    if (strpos($path, '*') !== FALSE) {
      $index = $mapper->getIndex();
      if (isset($item[$index])) {
        $item = $item[$index];
      }
    }

    if (is_array($item)) {
      if (array_filter($item)) {
        $item = reset($item);
      }
      else {
        $item = NULL;
      }
    }
    $items[0][$path] = $item;
  }
  $result->items = $items;

  // Loop through tamper plugins on the mapper.
  foreach ($cfe_mapper->tampers as $tamper) {
    if ($tamper->disabled) {
      continue;
    }

    $plugin = feeds_tamper_get_plugin($tamper->plugin_id);
    if (function_exists($plugin['callback']) && isset($result->items[0][$tamper->source])) {
      $path = $tamper->source;
      $field = &$result->items[0][$path];

      // Call any functions that have to alter the tamper before using
      // the feeds tamper plugin directly.
      $pre_callback = 'capx_tamper_' . $plugin['callback'];
      $key = 0;
      if (function_exists($pre_callback)) {
        $pre_callback($result, $key, $path, $field, $tamper->settings, $tamper->source);
      }

      // Call the feeds tamper. Then set that value back into the data array.
      $plugin['callback']($result, $key, $path, $field, $tamper->settings, $tamper->source);
      capx_tamper_set_data_by_json_path($data, $path, $field, $mapper->getIndex());
    }
  }
  $values['data'] = $data;
}

/**
 * Special handler for "Copy To" tamper.
 *
 * Switches it to a "Copy From" and flips the sources.
 *
 * @param object $result
 *   Results object with items property.
 * @param int $item_key
 *   Index of the item. Normally 0.
 * @param string $path
 *   JSON path string.
 * @param mixed $field
 *   String for most field results to manipulate.
 * @param array $settings
 *   CAPx Tamper settings.
 * @param string $source
 *   Original source.
 */
function capx_tamper_feeds_tamper_copy_callback(&$result, &$item_key, &$path, &$field, &$settings, &$source) {
  if ($settings['to_from'] == 'to') {
    $settings['to_from'] = 'from';
    $a = $path;
    $path = $settings['source'];
    $settings['source'] = $a;
  }
}

/**
 * Recursive function, given the object's data array, change a single value.
 *
 * @param array $data
 *   Object array from json response from API.
 * @param string $path
 *   JSON string path to desired value.
 * @param mixed $value
 *   New value to set.
 * @param int $index
 *   For wildcard items, change the correct indexed item.
 */
function capx_tamper_set_data_by_json_path(&$data, $path, $value, $index = 0) {
  $path = trim($path, '$.');

  $paths = explode('.', $path);
  $piece = array_shift($paths);

  // End of path.
  if (!$paths && isset($data[$piece])) {
    $data[$piece] = $value;
    return;
  }

  // Wildcard, replace the piece with the index value.
  if ($piece == '*') {
    $piece = $index;
  }

  if (isset($data[$piece])) {
    capx_tamper_set_data_by_json_path($data[$piece], implode('.', $paths), $value, $index);
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function capx_tamper_form_stanford_capx_mapper_form_alter(&$form, &$form_state, $form_id) {
  $mapper_name = FALSE;

  if ($form['naming']['machine-name']['#default_value']) {
    $mapper_name = $form['naming']['machine-name']['#default_value'];
  }

  $form['tampers'] = array(
    '#type' => 'fieldset',
    '#title' => t('Tamper'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#weight' => 1,
    '#tree' => TRUE,
  );

  // Move the submit buttons to the bottom.
  $form['actions']['#weight'] = 100;

  if (!$mapper_name) {
    $form['tampers']['info'] = array(
      '#markup' => t('Configure and save the mapper before configuring tampers.'),
    );
    return;
  }

  $form['tampers']['intro'] = array(
    '#markup' => "<p>" . t("Tampers allow you to manipulate items from the API before saving the data. For example, you can create a tamper that would strip html tags, or replace strings etc.") . "<p>",
  );

  $cta = "<br/><p>";
  $cta .= l(t('Manage "!name" Tampers', array('!name' => $form_state['build_info']['args'][0]->title)), CAPX_TAMPER . "/$mapper_name/tamper", array("attributes" => array("class" => 'button')));
  $cta .= "</p>";
  $cta .= "<span><em>" . t("Clicking this button will navigate you away to a new page. Please save your work first.") . "</em></span>";

  $form['tampers']['cta'] = array(
    '#markup' => $cta,
  );
}

/**
 * Creates an HTML id/class attribute name.
 *
 * @param string $path
 *   JSON path.
 *
 * @return string
 *   HTML ready id/class converted from the path.
 */
function capx_tamper_table_id($path) {
  $path = trim($path, '$.');
  return preg_replace("/[^A-Za-z0-9 ]/", '-', $path);
}
