<?php

/**
 * @file
 * CAPx Filters module.
 */

define('CAPX_FILTERS_PAGE', 'admin/config/capx/mapper/edit');

/**
 * Implements hook_menu().
 */
function capx_filters_menu() {
  $items = array();

  $items[CAPX_FILTERS_PAGE . "/%/filters"] = array(
    'title' => 'Filters',
    'page callback' => 'capx_filters_list',
    'file' => 'capx_filters.forms.inc',
    'page arguments' => array(5),
    'access arguments' => array('administer capx'),
    'type' => MENU_CALLBACK,
  );

  $items[CAPX_FILTERS_PAGE . "/%/filters/add"] = array(
    'title' => 'Add New Filter',
    'page callback' => 'drupal_get_form',
    'file' => 'capx_filters.forms.inc',
    'page arguments' => array('capx_filters_edit', 5),
    'access arguments' => array('administer capx'),
    'type' => MENU_LOCAL_ACTION,
  );

  $items[CAPX_FILTERS_PAGE . "/%/filters/%/edit"] = array(
    'title' => 'Edit Filter',
    'page callback' => 'drupal_get_form',
    'file' => 'capx_filters.forms.inc',
    'page arguments' => array('capx_filters_edit', 5, 7),
    'access arguments' => array('administer capx'),
    'type' => MENU_CALLBACK,
  );

  $items[CAPX_FILTERS_PAGE . "/%/filters/%/delete"] = array(
    'title' => 'Edit Filter',
    'page callback' => 'drupal_get_form',
    'file' => 'capx_filters.forms.inc',
    'page arguments' => array('capx_filters_delete', 5, 7),
    'access arguments' => array('administer capx'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_capx_entity_presave_alter().
 *
 * @param EntityDrupalWrapper $entity
 * @param CAPx\Drupal\Mapper\EntityMapper $mapper
 */
function capx_filters_capx_entity_presave_alter(&$entity, $mapper) {
  $raw_entity = $entity->value();
  $config = $mapper->getConfig();
  if (isset($config['filters']) && $config['filters']) {
    $pass = TRUE;
    foreach ($config['filters'] as $i => $filter) {
      // Already failed a filter.
      if (!$pass) {
        break;
      }

      $item = NULL;
      if (isset($raw_entity->capx[$filter['key']])) {
        $item = $raw_entity->capx[$filter['key']];
      }
      if (is_array($item) && $item) {
        $item = reset($item);
      }
      // Handles TRUE/FALSE values.
      if (is_bool($item)) {
        if ($item) {
          $item = 'true';
        }
        else {
          $item = 'false';
        }
      }
      $item = strtolower("$item");
      switch ($filter['comparison']) {
        case '=':
          $pass = $item == $filter['value'] ? !$filter['exclude'] : $filter['exclude'];
          break;

        case '!=':
          $pass = $item != $filter['value'] ? !$filter['exclude'] : $filter['exclude'];
          break;

        case '>':
          $pass = $item > $filter['value'] ? !$filter['exclude'] : $filter['exclude'];
          break;

        case '<':
          $pass = $item < $filter['value'] ? !$filter['exclude'] : $filter['exclude'];
          break;

        case 'not empty':
          $pass = !is_null($item) ? !$filter['exclude'] : $filter['exclude'];
          break;

        case 'contains':
          $pass = strpos($item, $filter['value']) !== FALSE ? !$filter['exclude'] : $filter['exclude'];
          break;
      }
    }

    if (!$pass) {
      if (isset($mapper->settings['filters_delete']) && $mapper->settings['filters_delete']) {
        $entity->delete();
      }
      $entity->clear();
    }
  }

}


/**
 * Implements hook_capx_config_fields_alter().
 */
function capx_filters_capx_config_fields_alter($mapper, &$fields) {
  $config = $mapper->getConfig();
  if (isset($config['filters'])) {
    foreach ($config['filters'] as $i => $filter) {
//      if (!field_info_field("capx_filter_$i")) {
//        $field = array(
//          'field_name' => "capx_filter_$i",
//          'type' => 'text',
//        );
//        field_create_field($field);
//      }
//      if (!field_info_instance($config['entity_type'], "capx_filter_$i", $config['bundle_type'])) {
//        $instance = array(
//          'field_name' => "capx_filter_$i",
//          'entity_type' => $config['entity_type'],
//          'bundle' => $config['bundle_type'],
//        );
//        field_create_instance($instance);
//      }

      $fields["capx_filter_$i"] = array($filter['key']);
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function capx_filters_form_stanford_capx_mapper_form_alter(&$form, &$form_state, $form_id) {
  $mapper_name = FALSE;
  $filter_delete = 0;
  if ($form['naming']['machine-name']['#default_value']) {
    $mapper_name = $form['naming']['machine-name']['#default_value'];
    $mapper = $form_state['build_info']['args'][0];
    $filter_delete = $mapper->settings['filters_delete'];
  }
  $form['field-mapping']['filters'] = array(
    '#type' => 'fieldset',
    '#title' => t('Filters'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );
  if (!$mapper_name) {
    $form['field-mapping']['filters']['info'] = array(
      '#markup' => t('Configure and save the mapper before configuring filters.'),
    );
    return;
  }

  $form['field-mapping']['filters']['delete'] = array(
    '#type' => 'checkbox',
    '#title' => t('Delete Existing'),
    '#description' => t('If checked, existing content will be deleted if it does not pass the configured filters'),
    '#default_value' => $filter_delete,
  );
  $form['field-mapping']['filters']['info'] = array(
    '#markup' => l(t('Configure Filters'), CAPX_FILTERS_PAGE . "/$mapper_name/filters"),
  );

  array_unshift($form['#submit'], 'capx_filters_mapper_config_form_submit');
}

/**
 * Mapper configuration form submit.
 *
 * Sets a static variable to use later. This prevents the need to manipulate
 * existing save functionality.
 */
function capx_filters_mapper_config_form_submit($form, &$form_state) {
  /** @var \CAPx\Drupal\Entities\CFEntity $mapper */
  $mapper = capx_cfe_load_by_machine_name($form_state['values']['machine-name'], 'mapper');
  $filter_settings = &drupal_static(__FUNCTION__, array(
    'filters' => array(),
    'delete' => $form_state['values']['field-mapping']['filters']['delete'],
  ));
  if (isset($mapper->settings['filters'])) {
    $filter_settings['filters'] = $mapper->settings['filters'];
  }
}

/**
 * Implements hook_entity_presave().
 */
function capx_filters_entity_presave($entity, $type) {
  $filter_settings = drupal_static('capx_filters_mapper_config_form_submit', array());
  if ($type == 'capx_cfe' && array_filter($filter_settings)) {
    $entity->settings['filters'] = $filter_settings['filters'];
    $entity->settings['filters_delete'] = $filter_settings['delete'];
  }
}
