<?php

/**
 * @file
 * CAPx Filters module.
 */

/**
 * Implements hook_menu().
 */
function capx_filters_menu() {
  $items = array();

  $items['admin/config/capx/mapper/edit/%/filters'] = array(
    'title' => 'Filters',
    'page callback' => 'capx_filters_list',
    'file' => 'capx_filters.forms.inc',
    'page arguments' => array(5),
    'access arguments' => array('administer capx'),
    'type' => MENU_LOCAL_ACTION,
  );

  $items['admin/config/capx/mapper/edit/%/filters/add'] = array(
    'title' => 'Add New Filter',
    'page callback' => 'drupal_get_form',
    'file' => 'capx_filters.forms.inc',
    'page arguments' => array('capx_filters_edit', 5),
    'access arguments' => array('administer capx'),
    'type' => MENU_LOCAL_ACTION,
  );

  $items['admin/config/capx/mapper/edit/%/filters/%/edit'] = array(
    'title' => 'Edit Filter',
    'page callback' => 'drupal_get_form',
    'file' => 'capx_filters.forms.inc',
    'page arguments' => array('capx_filters_edit', 5, 7),
    'access arguments' => array('administer capx'),
    'type' => MENU_CALLBACK,
  );

  $items['admin/config/capx/mapper/edit/%/filters/%/delete'] = array(
    'title' => 'Edit Filter',
    'page callback' => 'drupal_get_form',
    'file' => 'capx_filters.forms.inc',
    'page arguments' => array('capx_filters_delete', 5, 7),
    'access arguments' => array('administer capx'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_capx_entity_presave_alter().
 *
 * @param EntityDrupalWrapper $entity
 *   Entity to be saved.
 * @param array $data
 * @param CAPx\Drupal\Mapper\EntityMapper $mapper
 */
function capx_filters_capx_entity_presave_alter(&$entity, $data, $mapper) {
  $config = $mapper->getConfig();
  if (isset($config['filters'])) {
    foreach ($config['filters'] as $filter) {
      $filter['value'] = strtolower($filter['value']);
      $item = $mapper->getRemoteDataByJsonPath($data, $filter['key']);
      if (is_array($item) && $item && count($item) == 1) {
        $item = reset($item);
      }
      else {
        $item = '';
      }

      // Handles TRUE/FALSE values.
      if (is_bool($item)) {
        if ($item) {
          $item = 'true';
        }
        else {
          $item = 'false';
        }
      }
      else {
        $item = "$item";
      }

      $filtered = FALSE;
      switch ($filter['comparison']) {
        case '=':
          if ($item != $filter['value']) {
            $filtered = TRUE;
          }
          break;

        case '>':
          if (((int) $item) <= ((int) $filter['value'])) {
            $filtered = TRUE;
          }
          break;

        case '<':
          if (((int) $item) >= ((int) $filter['value'])) {
            $filtered = TRUE;
          }
          break;

        case 'contains':
          if (strpos($item, $filter['value']) === FALSE) {
            $filtered = TRUE;
          }
          break;
      }

      if ($filter['exclude']) {
        if (!$filtered) {
          $entity->delete();
          $entity->clear();
        }
      }
      else {
        if ($filtered) {
          $entity->delete();
          $entity->clear();
        }
      }
    }
  }
}
